package spacexlaunches.main;

import spacexlaunches.main.ctrl.Ctrl;
import spacexlaunches.main.ihm.Ihm;
import spacexlaunches.main.wrk.Wrk;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class Main {

    private Ctrl ctrl;


    public void init(Object context) {
        ctrl = new Ctrl();
        Ihm ihm = new Ihm();
        Wrk wrk = new Wrk();
        ctrl.setRefIhm(ihm);
        ctrl.setRefWrk(wrk);
        wrk.setRefCtrl(ctrl);
        ihm.setRefCtrl(ctrl);
    }

    public void start() {
        ctrl.start();
    }

    public void stop() {
        ctrl.stop();
    }

    public void destroy() {
    }

}
