package spacexlaunches.main;

import static com.codename1.ui.CN.*;

import spacexlaunches.main.ctrl.Ctrl;
import spacexlaunches.main.ihm.Ihm;
import spacexlaunches.main.wrk.Wrk;
import com.codename1.components.SpanLabel;
import com.codename1.ui.Dialog;
import com.codename1.ui.Form;
import com.codename1.ui.layouts.BoxLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class Main {

    private Form current;
    private Ctrl ctrl;


    public void init(Object context) {
        ctrl = new Ctrl();
        Ihm ihm = new Ihm();
        Wrk wrk = new Wrk();
        ctrl.setRefIhm(ihm);
        ctrl.setRefWrk(wrk);
        wrk.setRefCtrl(ctrl);
        ihm.setRefCtrl(ctrl);
//  ctrl.start();
    }

    public void start() {
       /* if (current != null) {
            current.show();
            return;
        }*/

        ctrl.start();
           ctrl.isUserConnectedAndShowView();
        // System.out.println(getCurrentForm().getName());
        //  System.out.println("asdasd");
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
